version: '3'
services:
  node:
    restart: always
    depends_on:
      - mongo
    build: .
    ports:
      - 80:3000
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    volumes:
      - ./:/code
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=amongus123
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: