version: '3'
services:
  node:
    restart: always
    depends_on:
      - mongodb
    build: .
    ports:
      - 80:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017
      DB_NAME: chess
      ACCESS_TOKEN_SECRET: "negr"
    volumes:
      - ./:/code
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: